### ISSUE TITLE
多域名怎么处理

### ISSUE THREAD

**Issue by boyssimple** [AbooJan/AJNetworking#1]
如果是多个域名请求数据 的，怎么设置

**Comment by AbooJan** [comment]
在继承自 “ AJRequestBeanBase” 的类里面，重写方法 “- (NSString *)apiHost” 即可，该方法默认读取 全局配置的公用域名

**Comment by boyssimple** [comment]
我只在RequestBean模块中设置了是否缓存、时间60,这样不行

**Comment by AbooJan** [comment]
@boyssimple 你使用的是这个方法发起请求吗
```
+ (void)requestWithBean:(__kindof AJRequestBeanBase * _Nonnull)requestBean
          cacheCallBack:(AJRequestCallBack _Nonnull)cacheCallBack
           httpCallBack:(AJRequestCallBack _Nonnull)httpCallBack;
```

**Comment by boyssimple** [comment]
是的，有没有把缓存数据取出来，还有如果 没有缓存， 是否自动执行网络请求了 
 
------------------ 原始邮件 ------------------
发件人: "AbooJan"; 
发送时间: 2018年4月12日(星期四) 上午10:54
收件人: "AbooJan/AJNetworking"; 
抄送: "boyssimple"; "Mention"; 
主题: Re: [AbooJan/AJNetworking] 多域名怎么处理 (#1)

 

@boyssimple 你使用的是这个方法发起请求吗
 + (void)requestWithBean:(__kindof AJRequestBeanBase * _Nonnull)requestBean           cacheCallBack:(AJRequestCallBack _Nonnull)cacheCallBack            httpCallBack:(AJRequestCallBack _Nonnull)httpCallBack;

**Comment by boyssimple** [comment]
还有个问题，自从我加入缓存那个首页，就出来老是不加载数据，再刷新方法，就会去加载网络数据 
 
------------------ 原始邮件 ------------------
发件人: "AbooJan"; 
发送时间: 2018年4月12日(星期四) 上午10:54
收件人: "AbooJan/AJNetworking"; 
抄送: "boyssimple"; "Mention"; 
主题: Re: [AbooJan/AJNetworking] 多域名怎么处理 (#1)

 

@boyssimple 你使用的是这个方法发起请求吗
 + (void)requestWithBean:(__kindof AJRequestBeanBase * _Nonnull)requestBean           cacheCallBack:(AJRequestCallBack _Nonnull)cacheCallBack            httpCallBack:(AJRequestCallBack _Nonnull)httpCallBack;

**Comment by boyssimple** [comment]
我发现这个里经常不行，刷新再执行就可以了



网络检测没通过，首页请求时出现的，其他页面都没问题
