### ISSUE TITLE
有没有办法把参数以json的方式放在body里面提交请求？

### ISSUE THREAD

**Issue by dongguoju** [AbooJan/AJNetworking#2]
有没有办法不能把参数以json的方式放在body里面提交请求？

**Comment by AbooJan** [comment]
@dongguoju 目前没有做这个功能的支持，你可以自行修改 manager 类，自定义 request ，通过设置 body 来实现你的功能

**Comment by dongguoju** [comment]
我改的话会打乱我的pods，等你更新之后这个
我在pull一下。

**Comment by AbooJan** [comment]
@dongguoju 可以把 `- (HTTP_REQUEST_SERIALIZATION)requestSerialization;`  返回 `HTTP_REQUEST_SERIALIZATION_JSON ` ，默认是 form 形式.
